# -*- coding: utf-8 -*-
"""
WPS V7 统一客户端，供各 SKILL 复用。
认证仅支持环境变量 wps_sid（或 WPS_SID）。
时间参数统一为 UTC ISO 8601，与 API 时间戳在客户端内自动转换。
"""
from .base import WpsV7Client
from .calendar import (
    list_calendars,
    get_calendar,
    create_calendar,
    update_calendar,
    delete_calendar,
    list_events,
    get_event,
    list_free_busy,
    create_event,
    update_event,
    delete_event,
    batch_create_event_attendees,
    batch_delete_event_attendees,
)
from .time_util import (
    response_timestamps_to_iso,
    timestamp_to_iso_utc,
    iso_to_timestamp,
    iso_to_calendar_time,
)
from .users import get_current_user
from .contacts import search_users
from .meeting import (
    create_meeting,
    update_meeting,
    delete_meeting,
    get_meeting,
    list_meetings,
    list_meeting_participants,
    put_meeting_participants,
    delete_meeting_participants,
    list_meeting_room_levels,
    list_event_meeting_rooms,
    get_meeting_transcription,
    get_meeting_summary,
    list_started_meetings,
    meeting_get_recordings,
    get_recording_summary,
    get_recording_transcript,
    meeting_get_minutes,
    get_minute_summary,
    get_minute_transcript,
)
from .im import (
    get_chat_list,
    get_chat,
    list_chat_messages,
    has_at_tag,
    rich_text_from_markdown_with_mentions,
    send_message,
    recall_message,
    list_recent_chats,
    search_chats,
    search_messages,
    send_cloud_file,
    create_chat,
)
from .drive import (
    upload_simple,
    update_file,
    list_files,
    get_file,
    get_file_directly,
    get_link_meta,
    get_file_download_url,
    get_file_content,
    get_file_content_extract,
    get_drive_id,
    create_file,
    create_otl_document,
    search_files,
    convert_file,
    list_latest_items,
    list_star_items,
    batch_create_star_items,
    batch_delete_star_items,
    list_drive_labels,
    get_drive_label_meta,
    list_drive_label_objects,
    create_drive_label,
    batch_add_drive_label_objects,
    batch_remove_drive_label_objects,
    list_deleted_files,
    restore_deleted_file,
    move_file,
    copy_file,
    rename_file,
    save_as_file,
    check_name_exists,
    open_file_link,
    close_file_link,
)
from .airpage import write_airpage_content
from .dbsheet import (
    get_schema as dbsheet_get_schema,
    list_records as dbsheet_list_records,
    get_record as dbsheet_get_record,
    search_records as dbsheet_search_records,
    batch_create_records as dbsheet_batch_create_records,
    batch_update_records as dbsheet_batch_update_records,
    batch_delete_records as dbsheet_batch_delete_records,
    create_sheet as dbsheet_create_sheet,
    update_sheet as dbsheet_update_sheet,
    delete_sheet as dbsheet_delete_sheet,
    create_view as dbsheet_create_view,
    get_form_meta as dbsheet_get_form_meta,
    update_form_meta as dbsheet_update_form_meta,
)

__all__ = [
    "WpsV7Client",
    "get_current_user",
    "search_users",
    "list_calendars",
    "get_calendar",
    "create_calendar",
    "update_calendar",
    "delete_calendar",
    "list_events",
    "get_event",
    "list_free_busy",
    "create_event",
    "update_event",
    "delete_event",
    "batch_create_event_attendees",
    "batch_delete_event_attendees",
    "create_meeting",
    "update_meeting",
    "delete_meeting",
    "get_meeting",
    "list_meetings",
    "list_meeting_participants",
    "put_meeting_participants",
    "delete_meeting_participants",
    "list_meeting_room_levels",
    "list_event_meeting_rooms",
    "get_meeting_transcription",
    "get_meeting_summary",
    "list_started_meetings",
    "meeting_get_recordings",
    "get_recording_summary",
    "get_recording_transcript",
    "meeting_get_minutes",
    "get_minute_summary",
    "get_minute_transcript",
    "get_chat_list",
    "get_chat",
    "list_chat_messages",
    "has_at_tag",
    "rich_text_from_markdown_with_mentions",
    "send_message",
    "recall_message",
    "list_recent_chats",
    "search_chats",
    "search_messages",
    "send_cloud_file",
    "create_chat",
    "upload_simple",
    "update_file",
    "list_files",
    "get_file",
    "get_file_directly",
    "get_link_meta",
    "get_file_download_url",
    "get_file_content",
    "get_file_content_extract",
    "get_drive_id",
    "create_file",
    "create_otl_document",
    "search_files",
    "convert_file",
    "list_latest_items",
    "list_star_items",
    "batch_create_star_items",
    "batch_delete_star_items",
    "list_drive_labels",
    "get_drive_label_meta",
    "list_drive_label_objects",
    "create_drive_label",
    "batch_add_drive_label_objects",
    "batch_remove_drive_label_objects",
    "list_deleted_files",
    "restore_deleted_file",
    "move_file",
    "copy_file",
    "rename_file",
    "save_as_file",
    "check_name_exists",
    "open_file_link",
    "close_file_link",
    "write_airpage_content",
    "dbsheet_get_schema",
    "dbsheet_list_records",
    "dbsheet_get_record",
    "dbsheet_search_records",
    "dbsheet_batch_create_records",
    "dbsheet_batch_update_records",
    "dbsheet_batch_delete_records",
    "dbsheet_create_sheet",
    "dbsheet_update_sheet",
    "dbsheet_delete_sheet",
    "dbsheet_create_view",
    "dbsheet_get_form_meta",
    "dbsheet_update_form_meta",
    "timestamp_to_iso_utc",
    "iso_to_timestamp",
    "iso_to_calendar_time",
    "response_timestamps_to_iso",
]
